version: "3"
services:
  docker:
    image: docker:dind
    networks:
      - node-api
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - "docker-certs:/certs"
      - "node-api-workdir:/root/pipelines"
      - "./build/daemon.json:/etc/docker/daemon.json"
      - "tmp-dir:/root/workdir"
    ports:
      - "2376:2376"

  a-line-cli:
    image: hamstershare/a-line-cli:latest
    build:
      dockerfile: ./Dockerfile
    networks:
      - node-api
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - "docker-certs:/certs:ro "
      - "node-api-workdir:/root/pipelines"
      - "tmp-dir:/root/workdir"
    ports:
      - "8080:8080"

volumes:
  docker-certs: {}
  node-api-workdir: {}
  tmp-dir: {}
networks:
  node-api: {}
