version: 1.0
name: my-test2
stages:
  git-clone:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: https://gitee.com/mohaijiang/spring-boot-example.git
          branch: master
  ipfs:
    needs:
      - git-clone
    steps:
      - name: update ipfs
        uses: hamster-ipfs
        with:
          path: src